services:
  email-service:
    image: ghcr.io/thebrownhuman/emailserver:latest
    container_name: email-service
    ports:
      - "8085:8085"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - shivansh-network

networks:
  shivansh-network:
    external: true
